### ISSUE TITLE
next version nearest_station and station_distance

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-nutrient-transect#14]
edit metadata template missingValueCodeExplanation as "Distance greater than 2 km from NES-LTER standard station" and accommodate in the assembly code that if the first sample for a cast is assigned a station, then all other samples from that cast be assigned the same station

**Comment by sbeaulieu** [comment]
replace ‘station_distance’ with ‘distance_km’ column header from new API output

**Comment by ecrockford** [comment]
We want it to stay 'station_distance'

**Comment by katemorkeski** [comment]
Updated missing value code
