### ISSUE TITLE
cite additional nutrient data from NES-LTER cruises published in BCO-DMO

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-nutrient-transect#16]
additional data for nutrients from Niskins taken on NES-LTER cruises EN608, EN627, and EN644:
Jenkins, B. D., Bertin, M. (2021) Pseudo-nitzschia spp. cell counts, nutrients water temperature and salinity, and concentrations of the toxin domoic acid from weekly samples and offshore cruises with the Northeast U.S. Shelf (NES) Long-Term Ecological Research (LTER). Biological and Chemical Oceanography Data Management Office (BCO-DMO). (Version 1) Version Date 2021-04-05 [if applicable, indicate subset used]. doi:10.26008/1912/bco-dmo.847448.1 [access date]

**Comment by katemorkeski** [comment]
done
