### ISSUE TITLE
inconsistent variable missing values

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#24]
All variables use NaN for missing values except ammonium and station_distance. (So the other nutrients are all nan but not ammonium.) I'm not sure how that difference happened? Should we change all to NaN? At the very least ammonia should be changed

**Comment by joefutrelle** [comment]
This is probably a result of a mixed Python / R workflow. Consistently using NaN in the package makes sense to me.

**Comment by ecrockford** [comment]
This is in the -info file for variables. Joanne has fixed and will push soon.
