### ISSUE TITLE
methods data cleaning - update station description?

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#25]
Nut Data Cleaning paragraph initially states nearest station is calculated on a per cruise basis for cruise-specific station list. 
1) Do we want to change this statement to describe the new method of station location by point in time?
2) We then expand on specifics of when stations were moved. This seems to get a bit overly detailed for me, but it's already written..... if we keep the station specifics I think we should update to include that L7-L9 were moved at the start of 2023

**Comment by katemorkeski** [comment]
Edited. Pending Taylor's review.

**Comment by katemorkeski** [comment]
done
