### ISSUE TITLE
missing AR52

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#28]
AR52A had L11 - LTER specific nut need CTD bottle data. 
So old - maybe all these missing AR cruises are in WHOI DLA now

**Comment by sbeaulieu** [comment]
AR52A ship-processed btl available https://dlacruisedata.whoi.edu/AR/cruise/AR52-A/ctd/process/

**Comment by ecrockford** [comment]
bottle data already downloaded and avialble in vast
