### ISSUE TITLE
add OOI nut data

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#29]
Currently no OOI nutrient data has been integrated into data set. We serve OOI chl data so we should do that for nut data as well.

**Comment by ecrockford** [comment]
LTER sampling strategy on Pioneer cruises specifically skipped sampling some depths that we would normally have sampled in order to streamline sampling effort and cost.

**Comment by ecrockford** [comment]
change sample_id to text as opposed to number. gives error otherwise

**Comment by joannekoch** [comment]
correction to the above: the alternate_sample_id for OOI was in the form of `number-number` (i.e. 3-4, 6-2, etc) which is interpreted as character. change the alternate_sample_id to text as opposed to number.
