### ISSUE TITLE
adjust Data Package Usage Rights to reference OOI

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#34]
Match chl-transect package. 

Data Package Usage Rights include “For those data identified in the data table from the Ocean Observatories Initiative (OOI), see the Limitation of Liability and Disclaimer in the OOI User Terms and Conditions (https://oceanobservatories.org/how-to-use-acknowledge-and-cite-data/)."

**Comment by katemorkeski** [comment]
add text to intellectual_rights.txt

**Comment by ecrockford** [comment]
in intellectual_rights.txt manually add
