### ISSUE TITLE
add OOI in Peak and Org

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#36]
Match chl-transect

-	In People and Org the email listed for OOI is help@oceanobservatories.org
-      Creator: OOI CGSN Data Team (Ocean Observatories Initiative)-

**Comment by ecrockford** [comment]
Remove Jaxine

**Comment by joannekoch** [comment]
modified the personnel tab in nutrient-transect-info.xlsx
