### ISSUE TITLE
Acknowledge OOI as detailed in comment

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-nutrient-transect#37]
Match chl-transect

Under Projects – reference OOI as a related project – James Edson, jedson@whoi.du, P.I. Funding NSF Award OCE-1743430

Related issue #15  - to include RAPID and PHASE II

**Comment by katemorkeski** [comment]
Match chlorophyll metadata. 
-	Abstract
-	OOI CGSN Data Team (Ocean Observatories Initiative) 
-	project_id variable in data table – and option is OOI
-	Data Package Usage Rights include “For those data identified in the data table from the Ocean Observatories Initiative (OOI), see the Limitation of Liability and Disclaimer in the OOI User Terms and Conditions (https://oceanobservatories.org/how-to-use-acknowledge-and-cite-data/)
- -	Methods specifically including “Please note that OOI data are included here as a convenience to researchers wishing to use the data from both projects, and that the authoritative source for OOI data is the OOI Alfresco document server for Cruise Data from the Coastal Pioneer NES Array 
- -	In People and Org the email listed for OOI is [help@oceanobservatories.org](mailto:help@oceanobservatories.org)
-	Under Projects – reference OOI as a related project – James Edson, [jedson@whoi.du](mailto:jedson@whoi.du), P.I. Funding NSF Award OCE-1743430 ** update?? https://govtribe.com/award/federal-grant-award/cooperative-agreement-2244833

**Comment by katemorkeski** [comment]
done!
